const paragraphs = ["The extent to which we are influenced by moral stories can't be quantified. People have been telling these stories for a long time. These short stories in English can be fun, teach us important things, make us feel motivated and inspired, and tell us what is right and wrong. In this article, we will look at a few short moral stories in English for kids, which are both motivational and inspirational.",
                    "The moral stories first told many generations ago, have the power to change our lives. For, they impart wisdom, teach us life lessons, and inspire us to follow the right path in life. But with every generation, the world's changed, and people's lives became busier than ever before. And, while we grew up listening to moral stories and learning from them, sometimes, we don't have the time to tell them to our children. In fact, most of us don't even remember them. Because of our busy schedules, we expect our children to learn more from the Internet than from us. But is it the right thing to do?",
                    "To help you change the trend, and bond with your child, here are a few moral stories in English that both you and your child can read together. Or, you can read and narrate to your child at your convenience.",
                    "The protagonist of this story is a young shepherd boy living in a village. Every day, the boy would take his flock of sheep to graze on a nearby hill. One day, while the sheep were grazing, the boy felt bored and decided to play a prank on the people of his village. \"Wolf...Wolf!\" he cried out as loud as he could.",
                    "Listening to his cries for help, the villagers rushed to help. And, when they came close, he began laughing. When the villagers understood that the boy had fooled them, they were very angry. Warning him not to play the prank again, they returned.",
                    "A few days later, the villagers heard the boy's cries for help once again. And, this time, it was for real. However, the villagers were tired of being laughed at and didn't think that the boy was really in trouble. So, they ignored his cries for help. And, the wolf killed and ate all his sheep.",
                    "Being greedy about gold, Midas said, \"Everything I touch should turn to gold.\" God granted his wish and told him that, from the next day, everything he touched would turn to gold.",
                    "After a while, Midas felt hungry. He picked up a piece of bread to eat, but it turned to gold. When he picked up a glass of water to quench his thirst, it turned to gold as well. As Midas was thinking about what to do, his daughter rushed to him. And, when Midas touched her, she turned into a golden statue.",
                    "Miserable and teary-eyed, Midas no longer wanted the boon. He prayed to God and atoned for his greed. Pleased by Midas' prayer, God asked him to wash his hands in the nearby river to get rid of the golden touch."
];

